spring.application.name=nemesys
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=user
spring.datasource.password=password
spring.security.user.name=user
spring.security.user.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.driverClassName=org.h2.Driver
logging.level.org.springframework.security=DEBUG
server.port=443
server.servlet.context-path=/
server.ssl.enabled=true
server.ssl.key-store=classpath:nemesys_ssl.p12
server.ssl.key-store-password=nemesys
server.ssl.key-password=nemesys
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=nemesys
